# Generated by Django 5.1.3 on 2024-11-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_user_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
