# Generated by Django 5.1.2 on 2024-10-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=300)),
                (
                    "Images",
                    models.ImageField(
                        blank=True, null=True, upload_to="schools/images/"
                    ),
                ),
                ("awards", models.CharField(blank=True, max_length=300)),
                ("contacts", models.CharField(blank=True, max_length=15)),
                ("website", models.URLField(blank=True)),
            ],
        ),
    ]
