# Generated by Django 5.1.2 on 2024-10-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="school",
            old_name="awards",
            new_name="award",
        ),
        migrations.RenameField(
            model_name="school",
            old_name="contacts",
            new_name="contact",
        ),
        migrations.RenameField(
            model_name="school",
            old_name="Images",
            new_name="image",
        ),
    ]
