# Generated by Django 5.1.2 on 2024-10-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_rename_awards_school_award_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="facility",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
