# Generated by Django 5.1.2 on 2024-10-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_school_facility"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="boarding_status",
            field=models.CharField(
                choices=[("boarding", "Boarding"), ("non_boarding", "Non-boarding")],
                default="non_boarding",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="city",
            field=models.CharField(default="Kenya", max_length=200),
        ),
        migrations.AddField(
            model_name="school",
            name="county",
            field=models.CharField(default="Kenya", max_length=200),
        ),
        migrations.AddField(
            model_name="school",
            name="school_status_choice",
            field=models.CharField(
                choices=[("public", "public"), ("private", "private")],
                default="public",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="school_type",
            field=models.CharField(
                choices=[
                    ("kindergarten", "Kindergarten"),
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                ],
                default="primary",
                max_length=12,
            ),
        ),
    ]
