# Generated by Django 5.1.2 on 2024-10-29 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0005_school_boarding_status_school_city_school_county_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="school",
            old_name="school_status_choice",
            new_name="school_status",
        ),
    ]
