# Generated by Django 5.1.3 on 2024-11-18 17:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='schools/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi'])]),
        ),
        migrations.AlterField(
            model_name='school',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_audience', models.CharField(choices=[('parents', 'Parents'), ('teachers', 'Teachers'), ('public', 'Public')], default='public', max_length=200)),
                ('announcement', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/events/images/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schools.school')),
            ],
        ),
    ]
