# Generated by Django 5.1.3 on 2024-11-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_school_video_alter_school_profile_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
