# Generated by Django 5.1.3 on 2024-11-22 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_audience', models.CharField(choices=[('parents', 'Parents'), ('teachers', 'Teachers'), ('public', 'Public')], default='public', max_length=200)),
                ('announcement', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/events/images/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schools.school')),
            ],
        ),
    ]
