# Generated by Django 5.1.3 on 2024-11-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_remove_school_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='award',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
